version: '3.5'
services:
  restcontainer:
    container_name: rest
    build: ./restcontainer
    ports:
      - "8082:8080"
    networks:
      - appnetwork
    volumes:
      - ./restcontainer:/app
    command: java -jar /app/App.jar
  nodecontainer:
    container_name: node
    build: ./nodecontainer
    ports:
      - "3000:3000"
    networks:
      - appnetwork
    volumes:
      - ./nodecontainer:/app
      - /app/node_modules/
    depends_on:
      - restcontainer
    command: npm start --prefix /app
networks:
  appnetwork:
    driver: bridge
    name: appnet