version: '3.5'
services:
  testdbcontainer:
    container_name: testdb
    build: ./postgiscontainer
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=bathymetry
      - POSTGRES_PASSWORD=bathymetry
      - POSTGRES_DBNAME=bathymetry
      - ALLOW_IP_RANGE=<*>
  postgiscontainer:
    container_name: postgis
    build: ./postgiscontainer
    ports:
      - "5432:5432"
    networks:
      - appnetwork
    environment:
      - POSTGRES_USER=bathymetry
      - POSTGRES_PASSWORD=bathymetry
      - POSTGRES_DBNAME=bathymetry
    volumes:
      - dbdata:/var/lib/postgresql/data
  geoservercontainer:
    container_name: geoserver
    build: ./geoservercontainer
    ports:
    - "8081:8080"
    networks:
    - appnetwork
    depends_on:
      - postgiscontainer
    volumes:
      - geodata:/opt/geoserver/data_dir
networks:
  appnetwork:
    driver: bridge
    name: appnet
volumes:
  dbdata:
  geodata: