export const Commands = {
  FETCH_FEATURE_INFO: "FETCH_FEATURE_INFO",
  HANDLE_DRAG_BOX: "HANDLE_DRAG_BOX",
  ZOOM_TO_LAYER: "ZOOM_TO_LAYER",
  ZOOM_TO_FIT: "ZOOM_TO_FIT",
  TURN_ON_REGRESSION_SERVICE_INTERACTION:
    "TURN_ON_REGRESSION_SERVICE_INTERACTION",
  EMPTY: "EMPTY"
};
